### PR TITLE
adds chart

### PR DESCRIPTION
**Pull request by brjx**

### CODE REVIEW

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498012770" title="LGTM">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
@brjx: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/brjx/simpleappdb/pull/2#issuecomment-498012794):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498012855" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
New changes are detected. LGTM label has been removed.

**Comment by brjx** [comment]
@brjx: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013002):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013014" title="LGTM">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013057" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
/approve
--

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013241" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013284" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by Brzhk — APPROVED** [review]

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#pullrequestreview-244616942" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
New changes are detected. LGTM label has been removed.

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013404" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013510" title="LGTM">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
@brjx: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/brjx/simpleappdb/pull/2#issuecomment-498013559):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Review by Brzhk — APPROVED** [review]

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#pullrequestreview-244617108" title="Approved">Brzhk</a>*
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **brjx**

If they are not already assigned, you can assign the PR to them by writing `/assign @brjx` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by brjx** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

Approval requirements bypassed by manually added approval.

This pull-request has been approved by: *<a href="https://github.com/brjx/simpleappdb/pull/2#pullrequestreview-244617108" title="Approved">Brzhk</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=brjx%2Fsimpleappdb).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/brjx/simpleappdb/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
